### ISSUE TITLE
Invalid date

### ISSUE THREAD

**Issue by muygalan** [wowthemesnet/mediumish-theme-jekyll#103]
_Preface: I am using Windows 10 and using WSL._

I cloned a new copy of the Mediumish theme following the instructions [here](https://bootstrapstarter.com/bootstrap-templates/template-mediumish-bootstrap-jekyll/).

I am receiving the following error(s):

First command `jekyll serve --watch`
```
WARN: Unresolved specs during Gem::Specification.reset:
      rb-inotify (>= 0.9.7, ~> 0.9)
      rouge (< 4, >= 1.7)
WARN: Clearing out unresolved specs.
Please report a bug if this causes problems.
/var/lib/gems/2.4.0/gems/bundler-2.0.2/lib/bundler/runtime.rb:319:in `check_for_activated_spec!': You have already activated public_suffix 3.1.1, but your Gemfile requires public_suffix 3.0.3. Prepending `bundle exec` to your command may solve this. (Gem::LoadError)
        from /var/lib/gems/2.4.0/gems/bundler-2.0.2/lib/bundler/runtime.rb:31:in `block in setup'
        from /var/lib/gems/2.4.0/gems/bundler-2.0.2/lib/bundler/spec_set.rb:148:in `each'
        from /var/lib/gems/2.4.0/gems/bundler-2.0.2/lib/bundler/spec_set.rb:148:in `each'
        from /var/lib/gems/2.4.0/gems/bundler-2.0.2/lib/bundler/runtime.rb:26:in `map'
        from /var/lib/gems/2.4.0/gems/bundler-2.0.2/lib/bundler/runtime.rb:26:in `setup'
        from /var/lib/gems/2.4.0/gems/bundler-2.0.2/lib/bundler.rb:107:in `setup'
        from /var/lib/gems/2.4.0/gems/jekyll-3.8.6/lib/jekyll/plugin_manager.rb:50:in `require_from_bundler'
        from /var/lib/gems/2.4.0/gems/jekyll-3.8.6/exe/jekyll:11:in `<top (required)>'
        from /usr/local/bin/jekyll:23:in `load'
        from /usr/local/bin/jekyll:23:in `<main>'
```

So then I ran the following command `bundle exec jekyll serve --watch`:

```
Configuration file: /mnt/c/Users/muyga/Desktop/mediumish-theme-jekyll/_config.yml
            Source: /mnt/c/Users/muyga/Desktop/mediumish-theme-jekyll
       Destination: /mnt/c/Users/muyga/Desktop/mediumish-theme-jekyll/_site
 Incremental build: disabled. Enable with --incremental
      Generating...
             Error: could not read file /mnt/c/Users/muyga/Desktop/mediumish-theme-jekyll/vendor/bundle/gems/jekyll-3.8.5/lib/site_template/_posts/0000-00-00-welcome-to-jekyll.markdown.erb: Invalid date '<%= Time.now.strftime('%Y-%m-%d %H:%M:%S %z') %>': Document 'vendor/bundle/gems/jekyll-3.8.5/lib/site_template/_posts/0000-00-00-welcome-to-jekyll.markdown.erb' does not have a valid date in the YAML front matter.
             ERROR: YOUR SITE COULD NOT BE BUILT:
                    ------------------------------------
                    Invalid date '<%= Time.now.strftime('%Y-%m-%d %H:%M:%S %z') %>': Document 'vendor/bundle/gems/jekyll-3.8.5/lib/site_template/_posts/0000-00-00-welcome-to-jekyll.markdown.erb' does not have a valid date in the YAML front matter.
```
Any ideas of what could be wrong?

**Comment by tgeorgetom** [comment]
Even I am getting this same issue. @muygalan did you get a solution for this issue.?

**Comment by rizkytegar** [comment]
I also have this problem

**Comment by kamaravichow** [comment]
I found the answer ....

It seems that you need to place the line exclude: [vendor] in _config.yml

found this on the following Github issue: https://github.com/jekyll/jekyll/issues/2938
